# -*- coding: utf-8 -*-
"""COVID-19 Retrenchment Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yu-cEHyH3PzgY0-RUbXEB9oK2Kx4Ahnp

# **Project: COVID-19 Analyzer on Retrenchment**
```
Aim: Give users better insight of    the COVID-19 situation on the retrenchment rate to help them make informed decisions
```


#### From the data gathered, users can use the tool to:
1. Educate themselves on the potential job stability during the pandemic
2. Help them decide what potential jobs they can look for during the pandemic

# 1. Read the dataset
I will first go ahead and read in the COVID-19 dataset
"""

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from dash import Dash, html, dcc, Input, Output, State, dash_table
import dash_bootstrap_components as dbc
import plotly.express as px
from apps.app import app #own file

# Read COVID-19 dataset
data=pd.read_excel("../csv/data-2022-10-14T073337-284.xlsx",sheet_name="transformed_data")

"""The dataset reveals the effects of the global economy on Singapore during the pandemic.

The following columns are:
###### 1. CODE
###### 2. COUNTRY
###### 3. DATE
###### 4. HDI (Human Development Index)
###### 5. TC (Total Cases)
###### 6. TD (Total Deaths)
###### 7. STI (Strigency Index)
###### 8. POP (Population)
###### 9. GDPCAP ($)
"""

# Print column names
#print(data.columns)

"""# 2. Clean the dataset

Firstly, I would like to filter the country columns by selecting Singapore
"""

# Filter: Only Singapore
data=data[data["COUNTRY"]=="Singapore"]

"""Next, I would like to convert the data type of the Date column to Date type"""

# Convert date data type to date format
data["DATE"] = pd.to_datetime(data["DATE"], format = '%Y-%m-%d')

"""Followed by filling up the missing values with average values"""

# Replace missing values with mean values
data = data.replace([np.inf, -np.inf], np.nan)
data = data.fillna(data.mean())
data.head()

"""Finally, I would like to segregate the date to day, month and year in order to merge with the retrenchment dataset later on"""

# Segregate the date to day, month and year
data["day"] = data["DATE"].dt.day
data["month"] =data["DATE"].dt.month
data["year"] = data["DATE"].dt.year

"""# 3. Explore the dataset
I am now going to explore the HDI variable in my dataset

### 3.1 HDI (Human Development Index)
It measures the country's average achievement in terms of health, knowledge and standard of living

*Reference :http://hdr.undp.org/en/content/human-development-index-hdi*

```
Aim: Identify if HDI has an impact on Singapore's economy during the pandemic 
```

Results: There is no indication that HDI is being affected by COVID-19 as the rate is normal since there is no variation in the data values

---

Therefore, HDI is not a good variable to use for my retrenchment visualizations later on
"""

data.plot.scatter(x='POP', y='HDI')
plt.xticks(rotation=90)

"""Next, I am going to explore the STI variable in my dataset

### 3.2 STI (Strigency Index)
It is a government response tracker that measures the containment policies such as school and workplace closures, stay-at-home policies, etc.

*Reference : https://www.civilsdaily.com/news/what-is-stringency-index/*

```
Assume: Affects the retrenchment rate in Singapore due to the closures which will cause many people to lose their jobs in various industries
```

```
Aim: To see how STI is performing everyday during COVID-19
```

Results: There is a pattern across the whole month (1-30days) for 2 years


---


Therefore, STI seems to be a good variable to use for my retrenchment visualizations later on
"""

fig, ax = plt.subplots(figsize = (15, 6))

sns.lineplot(data, x= "month", y ="STI", hue = data["day"], palette = "magma_r")

ax.set_title("Seasonal STI")
ax.set_xlabel("day")
ax.set_ylabel("STI")

data.plot.scatter(x='POP', y='STI',color="red")
plt.xticks(rotation=90)

"""I did a distributional plot to have a clearer view of my insights

---

Results: STI seems to be high for the past 2 years where a lot of them falls along 3.8



```
The distributional plot is skewed towards the right which tells me that COVID-19 has an impact on Singapore's STI
```
"""

f, axes = plt.subplots(1,1, figsize = (16, 5))
g1 = sns.distplot(data["STI"], color="red",ax = axes)
plt.title("Distributional of STI")

"""### 3.3 GDPCAP
It measures the country's economic activity *(↑ GDPCAP = ↓ population)*

Once you do the math, the wealth is spread among fewer people, which raises a country's GDP


*Reference : https://www.thebalance.com/gdp-per-capita-formula-u-s-compared-to-highest-and-lowest-3305848*



```
Aim: Tell me how prosperous a country feels to each of its citizens by measuring the country's standard of living through GDPCAP
```

Results: There is no indication that GDPCAP is being affected by COVID-19 as the rate is normal since there is no variation in the data values

---

Therefore, GDPCAP is not a good variable to use for my retrenchment visualizations later on
"""

fig, ax = plt.subplots(figsize = (15, 6))

sns.lineplot(data, x="month",y="GDPCAP", hue = data["day"], palette = "magma_r")

ax.set_title("Seasonal GDPCAP")
ax.set_xlabel("day")
ax.set_ylabel("GDPCAP")

data.plot.scatter(x='POP', y='GDPCAP',color="orange")
plt.xticks(rotation=90)

"""### 3.4 TC (Total Cases)

```
Assume: Affects the retrenchment rate in Singapore due to the number of COVID-19 cases which will cause many people to WFH 

However, some industries do not have WFH policies where retrenchment will jump into the picture
```

I plotted a time-series plot to view the number of COVID-19 cases in Singapore
"""

built_TC = data['TC'].value_counts().sort_index()
fig, ax = plt.subplots(1, 1, figsize=(18, 5))

ax.plot(built_TC.index, built_TC, color='#d1495b')

for s in ['top', 'right']:
    ax.spines[s].set_visible(False)

ax.grid()

#plt.show()

"""### 3.5 TD (Total Deaths)

```
I do not see any logic between total deaths and retrenchment rate
```
"""

#Inspired by this notebook : https://www.kaggle.com/gergelycsords/impact-of-covid-19-pandemic-some-visualization

import matplotlib.dates as md
fig1, ax = plt.subplots(figsize = (15, 6))

sns.lineplot(data=data, x='DATE', y='TD', hue='COUNTRY', legend=False, palette='Accent_r')

ax.set_title("Total deaths by countries")
ax.set_xlabel("Date")
ax.set_ylabel("Counts")

ax.xaxis.set_major_formatter(md.DateFormatter('%Y-%m-%d'))

"""#### Inspecting time series and rolling mean
Rolling means (moving averages) are generally used to smooth out short-term fluctuations in time series data and highlight long-term trends
"""

#Inspecting time series and rolling mean: (Take the average of the last 12-months)

crossing1 = data[['DATE', 'TD']].groupby('DATE').sum()
tseries = data.groupby(['DATE'])['TD'].agg(
    ['sum']).reset_index().rename(columns={'sum': 'TD'})

tseries = tseries.set_index('DATE')

fig = plt.subplots(figsize=(20, 8))

g = sns.lineplot(x=tseries.index, y='TD',
                 data=tseries, label="Actual Time Series")

rmean = crossing1.rolling(12, win_type='triang').mean()

g = sns.lineplot(x=rmean.index, y='TD',
                 data=rmean, label="Rolling Mean 12 Months")

plt.legend(fontsize='xx-large')
#plt.show()

built_TD = data['TD'].value_counts().sort_index()
fig, ax = plt.subplots(1, 1, figsize=(18, 5))

ax.plot(built_TD.index, built_TD, color='#66a182')

for s in ['top', 'right']:
    ax.spines[s].set_visible(False)

ax.grid()

#plt.show()

"""Now, to take a look at my overall COVID-19 dataset for further visualizations"""

def impact(x):
    y = data[['CODE','COUNTRY','DATE','HDI','TC','TD','STI','POP','GDPCAP']][data["COUNTRY"] == x]
    y = y.sort_values(by="CODE",ascending=False)
    return y.head(15)
impact("Singapore")

"""Results: 
1. Noticed that HDI and GDPCAP are constant
2. Noticed that there is some pattern going on in TD, TC and STI


---
**In this case, I have decided to use `TC` and `STI` as my indicator for my retrenchment visualizations**
"""

HDI= data[data['COUNTRY']=='Singapore'].groupby(['DATE']).agg({'HDI':['sum']})
GDPCAP = data[data['COUNTRY']=='Singapore'].groupby(['DATE']).agg({'GDPCAP':['sum']})
total1= HDI.join(GDPCAP)

TD= data[data['COUNTRY']=='Singapore'].groupby(['DATE']).agg({'TD':['sum']})
TC = data[data['COUNTRY']=='Singapore'].groupby(['DATE']).agg({'TC':['sum']})
total2= TD.join(TC)

POP= data[data['COUNTRY']=='Singapore'].groupby(['DATE']).agg({'POP':['sum']})
STI = data[data['COUNTRY']=='Singapore'].groupby(['DATE']).agg({'STI':['sum']})
total3= POP.join(STI)

plt.figure(figsize=(15,10))

plt.subplot(2, 2, 1)
total1.plot(ax=plt.gca(), title='Singapore')
plt.ylabel("Counts", size=13)


plt.subplot(2, 2, 2)
total2.plot(ax=plt.gca(), title='Singapore')
plt.ylabel("Counts", size=13)


plt.subplot(2, 2, 3)
total3.plot(ax=plt.gca(), title='Singapore')
plt.ylabel("Counts", size=13)

#print(total2)

"""# 4. Grouping all datasets together

The COVID-19's date column is in day type while the retrenchment dataset is in year type

Thus, due to the mismatched of the granularity data, I have decided to standardize the date type to yearly in order to merge the datasets later on
"""

# Standardize the date data format to yearly
import os
dfyearnumerical=data.groupby(['COUNTRY','year']).agg({'HDI': ['sum'],'TC': ['sum'],'TD': ['sum'],'STI': ['sum'],'POP': ['sum'],'GDPCAP': ['sum']}).reset_index()

"""# 4. Final Dataset
I will first go ahead and read in the retrenchment dataset
"""

# Read retrenchment dataset
import os
df_industry= pd.read_csv("../csv/retrench_industry_yearly.csv")

#print(dfyearnumerical.head())

"""Finally, I have merged the COVID-19 dataset and the retrenchment dataset together for deeper visualizations"""

# Final dataset combined
finalindustry = df_industry.merge(dfyearnumerical, on='year', how='left')

"""This is the final dataset containing the merged data"""

#print(finalindustry.head())

"""Followed by filling up the missing values with '0'"""

# Replace missing values with '0'
finalindustry=finalindustry.fillna(0)

"""Next, I will be filtering the years to recent 4 years for better visualization"""

# Print the recent 4 years from 2018 to 2021
finalindustry=finalindustry[finalindustry["year"]>2017]

"""I decided to plot a bar chart to take a look at the retrenchment rate over the years by industry type


---


Results: 2020 seems to have the highest number of retrenchment rate in various industries over the last 4 years

```
Infer: COVID-19 has caused a huge impact on the retrenchment rate
```


"""
import plotly.graph_objects as go
from plotly.subplots import make_subplots

#that huge bar graph
finalindustry = finalindustry[finalindustry.retrench != '-'] #quick fix pt 2?
finalindustry['retrench'] = finalindustry['retrench'].astype('int') #quick fix?
# Bar plot of retrenchment rate over the years by industry type
plt.rcParams['figure.figsize']=(17,7)
sns.set(style="whitegrid")
chart=sns.barplot(data=finalindustry, x="industry3", y="retrench", hue="year", palette="pastel")
chart.set_xticklabels(chart.get_xticklabels(), rotation=45, horizontalalignment='right')

fig_retrenchment = px.line(finalindustry,  x='year', y='retrench', color='industry3', #facet_col='year',
            labels=dict(industry1 = 'Industries', retrench = 'Number of Workers Retrenched', construction='Construction')
            )
#fig_retrenchment.update_xaxes(ticklabelstep = 1)
fig_retrenchment.update_xaxes(ticktext=['2018','2019','2020','2021'], tickvals=['2018','2019','2020','2021'])

fig = go.Figure()

fig.update_layout(
    template="simple_white",
    xaxis=dict(title_text="Year"),
    yaxis=dict(title_text="Count"),
    barmode="stack",
)

colors = ["#2A66DE", "#FFC32B","#d4c2b6","#b5829b"]
#print(finalindustry.industry1.unique())
figureArray = []
figureDict = {}
namelist = []
for r, c in zip(finalindustry.industry1.unique(), colors):
    #print(r)
    plot_df = finalindustry[finalindustry.industry1 ==r]
    title = r.capitalize()
    # Create figure with secondary y-axis
    fig = make_subplots(specs=[[{"secondary_y": True}]])
    fig.add_trace(
        go.Bar(x=[plot_df.year, plot_df.industry1], y=plot_df['retrench'], name=r, marker_color=c),
    )
    fig.add_trace(
        go.Scatter(x=[plot_df.year, plot_df.industry1], y=plot_df[('TC', 'sum')], name="TC"),
        secondary_y=True,)
    fig.add_trace(
        go.Scatter(x=[plot_df.year, plot_df.industry1], y=plot_df[('STI', 'sum')], name="STI"),
        secondary_y=True,)
    fig.update_layout(title=title)
    fig.update_xaxes()
    figureArray.append(fig)
    figureDict.update({r:fig})
    namelist.append(r)
#    fig.show()

import plotly.graph_objects as go
from plotly.subplots import make_subplots


fig = go.Figure()

fig.update_layout(
    template="simple_white",
    xaxis=dict(title_text="Year"),
    yaxis=dict(title_text="Count"),
    barmode="stack",
)

colors = ["#2A66DE", "#FFC32B","#d4c2b6","#b5829b","#025097","#1c96d2","#fdcc09","#f9a01b","#e81c75","#29c84f","#2bccb0","#bbdfff","#4ca2ee","#ff75b6","#107fb4","#31c9c6","#fcbb30","#eb3f67","#8545d8","#0f9ce2"]
#print(finalindustry.industry2.unique())
for r, c in zip(finalindustry.industry2.unique(), colors):
    #print(r)
    plot_df = finalindustry[finalindustry.industry2 ==r]
    title = r.capitalize()
    # Create figure with secondary y-axis
    fig = make_subplots(specs=[[{"secondary_y": True}]])
    fig.add_trace(
        go.Bar(x=[plot_df.year, plot_df.industry2], y=plot_df['retrench'], name=r, marker_color=c),
    )
    fig.add_trace(
        go.Scatter(x=[plot_df.year, plot_df.industry2], y=plot_df[('TC', 'sum')], name="TC"),
        secondary_y=True,)
    fig.add_trace(
        go.Scatter(x=[plot_df.year, plot_df.industry2], y=plot_df[('STI', 'sum')], name="STI"),
        secondary_y=True,)
    fig.update_layout(title=title)
    figureArray.append(fig)
    figureDict.update({r:fig})
    namelist.append(r)

#    fig.show()


layout = html.Div(children=[
    html.H1("Analysis of COVID-19 effects on Retrenchment"),
    html.P(children = ["""
    The COVID-19 pandemic affects different sectors of the Singapore economy to varying degrees, as shown in the visualizations below""",
    html.Br(), html.Br(),
    """
    The services sector includes global and domestic travel restrictions to stem the spread of COVID-19, which has resulted in a significant drop in tourist arrivals to Singapore and international air travel in general. As illustrated in the services sector below, restrictions have significantly impacted the accommodation, air transportation, and support services sectors, as well as the arts, entertainment, and recreation sectors.
    Similarly, decreased domestic consumption and travel significantly impact consumer-facing industries such as food and beverage services, retail trade, and many others.""", 
    html.Br(), html.Br(),
    """
    Outward-oriented manufacturing industry sectors, such as wholesale and retail trade, transportation, and storage, have been negatively impacted by the drop in external demand and supply chain disruptions.
    Furthermore, sentiment-sensitive sectors such as finance and insurance have seen increased volatility due to increased uncertainty and concerns about the spread of COVID-19. """,
    html.Br(),html.Br(),
    """
    Finally, domestically-oriented sectors such as construction, real estate, and other business services sectors have been negatively impacted by the decline in domestic economic activity and weaker sentiments. Furthermore, the construction industry is expected to experience manpower disruptions soon due to additional measures implemented to combat the spread of COVID-19 at construction sites and dormitories.
    """
    ]),
    html.Br(),
            #show final graphs
    html.Div(children=[
            dcc.Graph(figure = fig_retrenchment, id = 'mainRetGraph'),
            dcc.Checklist(id = 'checklist', 
                options= finalindustry.industry1.unique(), 
                value= finalindustry.industry1.unique(),
                inline = True
            ),
            html.Div(id='fig0', children=dcc.Graph(figure = figureDict[namelist[0]])),
            html.Div(id='fig1', children=dcc.Graph(figure = figureDict[namelist[1]])),
            html.Div(id='fig2', children=dcc.Graph(figure = figureDict[namelist[2]])),
            html.Div(id='fig3', children=dcc.Graph(figure = figureDict[namelist[3]])),
            html.Div(id='fig4', children=dcc.Graph(figure = figureDict[namelist[4]])),
            html.Div(id='fig5', children=dcc.Graph(figure = figureDict[namelist[5]])),
            html.Div(id='fig6', children=dcc.Graph(figure = figureDict[namelist[6]])),
            html.Div(id='fig7', children=dcc.Graph(figure = figureDict[namelist[7]])),
            html.Div(id='fig8', children=dcc.Graph(figure = figureDict[namelist[8]])),
            html.Div(id='fig9', children=dcc.Graph(figure = figureDict[namelist[9]])),
            html.Div(id='fig10', children=dcc.Graph(figure = figureDict[namelist[10]])),
            html.Div(id='fig11', children=dcc.Graph(figure = figureDict[namelist[11]])),
            html.Div(id='fig12', children=dcc.Graph(figure = figureDict[namelist[12]])),
            html.Div(id='fig13', children=dcc.Graph(figure = figureDict[namelist[13]])),
            html.Div(id='fig14', children=dcc.Graph(figure = figureDict[namelist[14]])),
            html.Div(id='fig15', children=dcc.Graph(figure = figureDict[namelist[15]])),
            html.Div(id='fig16', children=dcc.Graph(figure = figureDict[namelist[16]])),
            html.Div(id='fig17', children=dcc.Graph(figure = figureDict[namelist[17]])),
            html.Div(id='fig18', children=dcc.Graph(figure = figureDict[namelist[18]])),
            html.Div(id='fig19', children=dcc.Graph(figure = figureDict[namelist[19]])),
            html.Div(id='fig20', children=dcc.Graph(figure = figureDict[namelist[20]])),
            html.Div(id='fig21', children=dcc.Graph(figure = figureDict[namelist[21]])),
    ]),
    html.H4("Conclusion:"),
    html.P("""The economy has some bright spots, including new opportunities with increased demand for online sales, services, and healthcare services. However, the global and Singapore economies must be closely monitored in the coming months as the COVID-19 situation remains fluid. Domestically, how the Singapore retrenchment rate performs for the rest of the year will be determined by our ability to resume economic activities safely and without a resurgence of infections in the community."""),
])
@app.callback([Output('mainRetGraph', 'figure'),
Output('fig0', 'children'),
Output('fig1', 'children'),
Output('fig2', 'children'),
Output('fig3', 'children'),
Output('fig4', 'children'),
Output('fig5', 'children'),
Output('fig6', 'children'),
Output('fig7', 'children'),
Output('fig8', 'children'),
Output('fig9', 'children'),
Output('fig10', 'children'),
Output('fig11', 'children'),
Output('fig12', 'children'),
Output('fig13', 'children'),
Output('fig14', 'children'),
Output('fig15', 'children'),
Output('fig16', 'children'),
Output('fig17', 'children'),
Output('fig18', 'children'),
Output('fig19', 'children'),
Output('fig20', 'children'),
Output('fig21', 'children'),
],[Input('checklist','value')])
def updateRetGraph(industry):
    df = finalindustry
    mask = df.industry1.isin(industry)
    fig = px.line(df[mask],  x='year', y='retrench', color='industry3', #facet_col='year',
            labels=dict(industry1 = 'Industries', retrench = 'Number of Workers Retrenched', construction='Construction')
            )
    fig.update_xaxes(ticktext=['2018','2019','2020','2021'], tickvals=['2018','2019','2020','2021'])
    counter = 0
    divArray=[]
    
    for name in namelist:
        if name in df[mask].industry1.values or name in df[mask].industry2.values or name in df[mask].industry3.values:
            divArray.append(dcc.Graph(figure = figureDict[name]) )
            #divArray.append(html.P("yes"))
        else:
            divArray.append(html.Div())
        counter +=1
    
    return fig, divArray[0], divArray[1], divArray[2], divArray[3], divArray[4], divArray[5], divArray[6], divArray[7], divArray[8], divArray[9], divArray[10], divArray[11], divArray[12], divArray[13], divArray[14], divArray[15], divArray[16], divArray[17], divArray[18], divArray[19], divArray[20], divArray[21]